baseURL = "https://sage-csr.vercel.app"
languageCode = 'en-us'
title = 'Sage CS Research'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = ""
  # Author of the site, will be used in meta information
  author = "Sage-Code"
  # Description of the site, will be used in meta information
  description = "Computer Science Research"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = true
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # If set to false, a Home button will appear below the search bar on the menu.
  # It is redirecting to the landing page of the current language if specified. (Default is "/")
  disableLandingPageButton = true
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # If set to true, prevents Hugo from including the mermaid module if not needed (will reduce load times and traffic)
  disableMermaid = false
  # Specifies the remote location of the mermaid js
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  # ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "purple"
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  custom_css = ["css/foo.css", "css/bar.css"]
  # Change the title separator. Default to "::".
  titleSeparator = "-"

  landingPageURL = "/"
  landingPageName = "<i class='fas fa-home'></i> Home"

  relativeURLs = true

  startLevel = 2 
  # Define the starting heading level for TOC inclusion (e.g., 2 for H2).

  endLevel = 3 
  # Define the ending heading level for TOC inclusion (e.g., 5 for H5).

[[menu.shortcuts]] 
name = "<i class='fas fa-home'></i> Home"
identifier = "home"
url = "https://sage-cse.vercel.app"
weight = 90


[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/sage-code"
weight = 91


[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Hugo Doc"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 92

[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Credits"
url = "/_credits"
weight = 93

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 94